return {{[ [[top]] ] = {2},[ [[bottom]] ] = {3},[ [[windows]] ] = {4},[ [[right]] ] = {5},[ [[left]] ] = {6},[ [[sides]] ] = {7},},
{[ [[w]] ] = 985,[ [[h]] ] = 30,},
{[ [[w]] ] = 985,[ [[h]] ] = 65,},
{[ [[bottomRightContainer]] ] = {8},[ [[topLeftContainer]] ] = {9},[ [[topContainer]] ] = {10},[ [[bottomLeftContainer]] ] = {11},[ [[bottomContainer]] ] = {12},},
{[ [[w]] ] = 640,[ [[h]] ] = 379,},
{[ [[w]] ] = 295,[ [[h]] ] = 301,},
{[ [[top]] ] = [[disabled]],[ [[right]] ] = [[disabled]],[ [[left]] ] = [[disabled]],[ [[bottom]] ] = [[disabled]],},
{[1] = {13},},
{[1] = {14},},
{[1] = [[TopBar]],},
{[1] = {15},},
{[1] = [[BottomBar]],},
{[1] = [[Chat]],[2] = true,},
{[1] = [[People Here]],[2] = true,},
{[1] = [[Info Here]],[2] = true,},
}